version: '3.6'

services:

  trivial-navigo-server:
    container_name: trivial-navigo-server
    build:
            context: .
            dockerfile: ./apache/Dockerfile
    ports:
        - 8080:80
    links:
         - trivial-navigo-mysql

  trivial-navigo-mysql:
    container_name: trivial-navigo-mysql
    build:
            context: .
            dockerfile: ./mysql/Dockerfile
    ports:
        - 3306
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  trivial-navigo-phpmyadmin:
    container_name: trivial-navigo-phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
       - trivial-navigo-mysql:db
    ports:
        - 8081:80