version: '3.6'

services:

  php:
    container_name: php
    build:
            context: .
            dockerfile: ./apache/Dockerfile
    ports:
        - 8080:80
    links:
         - mysql

  mysql:
    container_name: mysql
    build:
            context: .
            dockerfile: ./mysql/Dockerfile
    ports:
        - 3306
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  trivial-navigo-phpmyadmin:
    container_name: trivial-navigo-phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
       - mysql:db
    ports:
        - 8081:80